export const EDITTING_TASK_SERVICE = "EDITTING_TASK_SERVICE";
export const CHANGED_TASK_SERVICE = "CHANGED_TASK_SERVICE";
export const CANCEL_TASK_SERVICE = "CANCEL_TASK_SERVICE";
export const EDIT_TASK_SERVICE = "EDIT_TASK_SERVICE";
export const ADD_TASK_SERVICE = "ADD_TASK_SERVICE";
export const REMOVE_TASK_SERVICE = "REMOVE_TASK_SERVICE";
export const SEARCH_CHANGE_FIELD_SERVICE = "SEARCH_CHANGE_FIELD_SERVICE";